#!/bin/bash

# Build the nasty URL of the day
URL='http://nomads.ncep.noaa.gov/cgi-bin/filter_gensbc.pl'
DATE=`date +%Y%m%d`
REGION='subregion=&leftlon=0&rightlon=360&toplat=90&bottomlat=-90'
FILE='file=ge10pt.t00z.pgrb2a_bcf06&lev_10_m_above_ground=on'
DIR='dir=%2Fgefs.'$DATE'%2F00%2Fpgrb2a_bc'

# Fetch it and put it in temp
curl -o temp/gfs.grib $URL'?'$FILE'&all_var=on&'$REGION'&'$DIR

# Convert it to an easier to use format (for the web)
grib2json -d -n -o temp/gfs.json temp/gfs.grib
